// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXa9qGqvdAQxChTZzwEoODJiSengQhMRA',
    appId: '1:800348276964:web:6b61b196275ec838b184f1',
    messagingSenderId: '800348276964',
    projectId: 'homz-d74f2',
    authDomain: 'homz-d74f2.firebaseapp.com',
    storageBucket: 'homz-d74f2.appspot.com',
    measurementId: 'G-P8YELXR846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxp6TzKZq-N22keo6FoC21-WS3nb3kAc',
    appId: '1:800348276964:android:88d6e785938067c7b184f1',
    messagingSenderId: '800348276964',
    projectId: 'homz-d74f2',
    storageBucket: 'homz-d74f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_76H5l7UDLa6FsOOzzTd290F4mcAWKQw',
    appId: '1:800348276964:ios:0047ba4421a8c10ab184f1',
    messagingSenderId: '800348276964',
    projectId: 'homz-d74f2',
    storageBucket: 'homz-d74f2.appspot.com',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_76H5l7UDLa6FsOOzzTd290F4mcAWKQw',
    appId: '1:800348276964:ios:0047ba4421a8c10ab184f1',
    messagingSenderId: '800348276964',
    projectId: 'homz-d74f2',
    storageBucket: 'homz-d74f2.appspot.com',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXa9qGqvdAQxChTZzwEoODJiSengQhMRA',
    appId: '1:800348276964:web:74c916b9eb007145b184f1',
    messagingSenderId: '800348276964',
    projectId: 'homz-d74f2',
    authDomain: 'homz-d74f2.firebaseapp.com',
    storageBucket: 'homz-d74f2.appspot.com',
    measurementId: 'G-8D418RV2R5',
  );
}
