// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35LHTyjkfX8CSepAGKGbQTL_btr5uTno',
    appId: '1:822141352330:web:40f4ba4ff59802437c3073',
    messagingSenderId: '822141352330',
    projectId: 'homz-3f8b5',
    authDomain: 'homz-3f8b5.firebaseapp.com',
    storageBucket: 'homz-3f8b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjuyLBzXfw8vyKICkW_Wf_O3cImqUuZCI',
    appId: '1:822141352330:android:e63d80ca1894d2cb7c3073',
    messagingSenderId: '822141352330',
    projectId: 'homz-3f8b5',
    storageBucket: 'homz-3f8b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJmsKXRY8g3kV3Op7WVWzONwFAJMsEdg',
    appId: '1:822141352330:ios:f84b920baeb1fb907c3073',
    messagingSenderId: '822141352330',
    projectId: 'homz-3f8b5',
    storageBucket: 'homz-3f8b5.appspot.com',
    androidClientId: '822141352330-b08m295ji8ohshug7tjrn6dgkc4cruk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJmsKXRY8g3kV3Op7WVWzONwFAJMsEdg',
    appId: '1:822141352330:ios:f84b920baeb1fb907c3073',
    messagingSenderId: '822141352330',
    projectId: 'homz-3f8b5',
    storageBucket: 'homz-3f8b5.appspot.com',
    androidClientId: '822141352330-b08m295ji8ohshug7tjrn6dgkc4cruk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.homez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB35LHTyjkfX8CSepAGKGbQTL_btr5uTno',
    appId: '1:822141352330:web:891729e64a1e29817c3073',
    messagingSenderId: '822141352330',
    projectId: 'homz-3f8b5',
    authDomain: 'homz-3f8b5.firebaseapp.com',
    storageBucket: 'homz-3f8b5.appspot.com',
  );
}
